name: Silence is a Virus
permalink: /:title
exclude: [Gemfile, Gemfile.lock]
assets:
  js_compressor:  uglifier
  css_compressor: sass
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/downloads